version: '3.9'

services:
  cassandra:
    container_name: cassandra
    image: docker.io/bitnami/cassandra:latest
    restart: always
    ports:
      - '7000:7000'
      - '9042:9042'
    volumes:
      - 'cassandra_data:/bitnami'
    environment:
      - CASSANDRA_CLUSTER_NAME=cassandra
      - CASSANDRA_SEEDS=cassandra
      - CASSANDRA_PASSWORD_SEEDER=yes
      - CASSANDRA_USER=admin
      - CASSANDRA_PASSWORD=root
    healthcheck:
      test: ["CMD-SHELL", "[ $$(nodetool statusgossip) = running ]"]
      interval: 15s
      timeout: 10s
      retries: 10

  redis-node-0:
    container_name: redis-0
    image: docker.io/bitnami/redis-cluster:latest
    restart: always
    ports:
      - '6380:6379'
    volumes:
      - redis-cluster_data-0:/bitnami/redis/data
    environment:
      - 'REDIS_PASSWORD=root'
      - 'REDIS_NODES=redis-node-0 redis-node-1'
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 15s
      timeout: 10s
      retries: 10

  redis-node-1:
    container_name: redis-1
    image: docker.io/bitnami/redis-cluster:latest
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - redis-cluster_data-1:/bitnami/redis/data
    depends_on:
      - redis-node-0
    environment:
      - 'REDIS_PASSWORD=root'
      - 'REDISCLI_AUTH=root'
      - 'REDIS_CLUSTER_REPLICAS=1'
      - 'REDIS_NODES=redis-node-0 redis-node-1'
      - 'REDIS_CLUSTER_CREATOR=yes'
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 15s
      timeout: 10s
      retries: 10

volumes:
  cassandra_data:
    driver: local
  redis-cluster_data-0:
    driver: local
  redis-cluster_data-1:
    driver: local
