version: '3.9'

services:
  cassandra:
    container_name: cassandra
    image: docker.io/bitnami/cassandra:latest
    restart: always
    ports:
      - '7000:7000'
      - '9042:9042'
    volumes:
      - 'cassandra_data:/bitnami'
    environment:
      - CASSANDRA_CLUSTER_NAME=cassandra
      - CASSANDRA_SEEDS=cassandra
      - CASSANDRA_PASSWORD_SEEDER=yes
      - CASSANDRA_USER=admin
      - CASSANDRA_PASSWORD=root
    healthcheck:
      test: ["CMD-SHELL", "[ $$(nodetool statusgossip) = running ]"]
      interval: 15s
      timeout: 10s
      retries: 10

  redis-node-0:
    container_name: redis-node-0
    image: docker.io/bitnami/redis-cluster:latest
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - redis-cluster_data-0:/bitnami/redis/data
    environment:
      - 'REDIS_PASSWORD=root'
      - 'REDIS_NODES=redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5'
    command: ["redis-server", "--bind", "redis", "--port", "6379"]
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 15s
      timeout: 10s
      retries: 10

  redis-node-1:
    container_name: redis-node-1
    image: docker.io/bitnami/redis-cluster:latest
    restart: always
    ports:
      - '6380:6380'
    volumes:
      - redis-cluster_data-1:/bitnami/redis/data
    environment:
      - 'REDIS_PASSWORD=root'
      - 'REDIS_NODES=redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5'
    command: ["redis-server", "--bind", "redis", "--port", "6380"]
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 15s
      timeout: 10s
      retries: 10

  redis-node-2:
    container_name: redis-node-2
    image: docker.io/bitnami/redis-cluster:latest
    restart: always
    ports:
      - '6381:6381'
    volumes:
      - redis-cluster_data-2:/bitnami/redis/data
    environment:
      - 'REDIS_PASSWORD=root'
      - 'REDIS_NODES=redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5'
    command: ["redis-server", "--bind", "redis", "--port", "6381"]
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 15s
      timeout: 10s
      retries: 10

  redis-node-3:
    container_name: redis-node-3
    image: docker.io/bitnami/redis-cluster:latest
    restart: always
    ports:
      - '6382:6382'
    volumes:
      - redis-cluster_data-3:/bitnami/redis/data
    environment:
      - 'REDIS_PASSWORD=root'
      - 'REDIS_NODES=redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5'
    command: ["redis-server", "--bind", "redis", "--port", "6382"]
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 15s
      timeout: 10s
      retries: 10

  redis-node-4:
    container_name: redis-node-4
    image: docker.io/bitnami/redis-cluster:latest
    restart: always
    ports:
      - '6383:6383'
    volumes:
      - redis-cluster_data-4:/bitnami/redis/data
    environment:
      - 'REDIS_PASSWORD=root'
      - 'REDIS_NODES=redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5'
    command: ["redis-server", "--bind", "redis", "--port", "6383"]
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 15s
      timeout: 10s
      retries: 10

  redis-node-5:
    container_name: redis-node-5
    image: docker.io/bitnami/redis-cluster:latest
    restart: always
    ports:
      - '6384:6384'
    volumes:
      - redis-cluster_data-5:/bitnami/redis/data
    depends_on:
      - redis-node-0
      - redis-node-1
      - redis-node-2
      - redis-node-3
      - redis-node-4
    environment:
      - 'REDIS_PASSWORD=root'
      - 'REDISCLI_AUTH=root'
      - 'REDIS_CLUSTER_REPLICAS=1'
      - 'REDIS_NODES=redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5'
      - 'REDIS_CLUSTER_CREATOR=yes'
    command: ["redis-server", "--bind", "redis", "--port", "6384"]
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 15s
      timeout: 10s
      retries: 10

volumes:
  cassandra_data:
    driver: local
  redis-cluster_data-0:
    driver: local
  redis-cluster_data-1:
    driver: local
  redis-cluster_data-2:
    driver: local
  redis-cluster_data-3:
    driver: local
  redis-cluster_data-4:
    driver: local
  redis-cluster_data-5:
    driver: local
