version: '3.9'

services:
  cassandra:
    container_name: cassandra
    image: docker.io/bitnami/cassandra:latest
    ports:
      - '7000:7000'
      - '9042:9042'
    volumes:
      - 'cassandra_data:/bitnami'
    healthcheck:
      test: ["CMD-SHELL", "[ $$(nodetool statusgossip) = running ]"]
      interval: 15s
      timeout: 10s
      retries: 10
    environment:
      - CASSANDRA_CLUSTER_NAME=cassandra
      - CASSANDRA_SEEDS=cassandra
      - CASSANDRA_PASSWORD_SEEDER=yes
      - CASSANDRA_USER=admin
      - CASSANDRA_PASSWORD=root
  redis:
    image: bitnami/redis:latest
    ports:
      - '6379:6379'
    volumes:
      - 'redis_data:/redis_data'
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 15s
      timeout: 10s
      retries: 10
    environment:
      - REDIS_REPLICATION_MODE=master
      - REDIS_PASSWORD=root
volumes:
  cassandra_data:
    driver: local
  redis_data:
    driver: local

