// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model_http

type QuestionCreate struct {
	Description string   `json:"Description"`
	Asset       string   `json:"Asset"`
	Options     []string `json:"Options"`
	Answers     []int32  `json:"Answers"`
}

type QuizCreate struct {
	Title       string            `json:"Title"`
	MarkingType string            `json:"MarkingType"`
	Questions   []*QuestionCreate `json:"Questions"`
}
